name: Contract Tests
description: Runs CI for the .NET Server SDK
inputs:
  service_project_file:
    description: 'Path to the contract test service project file.'
    required: true
  service_dll_file:
    description: 'Path where compiled dll will be found.'
    required: true
  token:
    description: 'Github token, used for contract tests'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup dotnet build tools
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0

    - name: Restore Workloads
      shell: bash
      run: dotnet workload restore ${{ inputs.service_project_file }}

    - name: Restore Dependencies
      shell: bash
      run: dotnet restore ${{ inputs.service_project_file }}

    - name: Build Contract Tests
      shell: bash
      run: dotnet build -p:Configuration=debug ${{ inputs.service_project_file }}

    - name: Launch Contract Tests
      id: launch-contract-tests
      shell: bash
      run: dotnet ${{ inputs.service_dll_file }} > test-service.log 2>&1 & disown

    - name: Suppression Path
      shell: bash
      run: echo "SUPPRESSION_FILE=$(dirname ./${{ inputs.service_project_file }})/test-supressions.txt" >> $GITHUB_ENV

    - name: Run Contract Tests
      uses: launchdarkly/gh-actions/actions/contract-tests@contract-tests-v1.0.2
      with:
        test_service_port: 8000
        extra_params: '--status-timeout=360,--skip-from=${{ env.SUPPRESSION_FILE }}'
        token: ${{ inputs.token }}
