name: Build Action
description: 'Dotnet Server SDK Build action.'
inputs:
  project_file:
    description: 'Path to the project file.'
    required: true

runs:
  using: composite
  steps:
    - name: Setup dotnet build tools
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0
          7.0

    - name: Copy global.json in place
      shell: bash
      run: cp global.example.json global.json

    - name: Display dotnet version
      shell: bash
      run: dotnet --version

    - name: Build
      shell: bash
      run: dotnet build -p:Configuration=Release ${{ inputs.project_file }}

    - name: Remove global.json
      shell: bash
      run: rm global.json