name: CI
description: Runs CI for the .NET Server SDK
inputs:
  project_file:
    description: 'Path to the project file.'
    required: true
  test_project_file:
    description: 'Path to the test project file.  If provided, run unit tests, otherwise skip them.'
    required: false

runs:
  using: composite
  steps:
    - name: Setup dotnet build tools
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
              6.0
              7.0

    - name: Restore Workloads
      shell: bash
      run: dotnet workload restore ${{ inputs.project_file }}

    - name: Restore Dependencies
      shell: bash
      run: dotnet restore ${{ inputs.project_file }}

    - name: Build
      shell: bash
      run: dotnet build -p:Configuration=debug ${{ inputs.project_file }}

    - name: Run Unit Tests
      if: ${{ inputs.test_project_file != '' }}
      shell: bash
      run: |
        dotnet restore ${{ inputs.test_project_file }}
        dotnet test --framework=net6.0 ${{ inputs.test_project_file }}
