name: LaunchDarkly.ServerSdk CI
on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Env from project's Env file
        shell: bash
        run: echo "$(cat pkgs/sdk/server/github_actions.env)" >> $GITHUB_ENV

      - uses: ./.github/actions/ci
        with:
          project_file: ${{ env.PROJECT_FILE}}
          test_project_file: ${{ env.TEST_PROJECT_FILE}}

      - uses: ./.github/actions/contract-tests
        with:
          service_project_file: ${{ env.CONTRACT_TEST_PROJECT_FILE}}
          service_dll_file: ${{ env.CONTRACT_TEST_DLL_FILE}}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build-docs
        with:
          workspace_path: ${{ env.WORKSPACE_PATH}}
