name: LaunchDarkly.ServerSdk CI
on:
  push:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md' # Do not need to run CI for markdown changes.
  pull_request:
    branches: [main, 'feat/**']
    paths-ignore:
      - '**.md'

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: launchdarkly/gh-actions/actions/release-secrets@release-secrets-v1.0.1
        name: Get secrets
        with:
          aws_assume_role: ${{ vars.AWS_ROLE_ARN }}

      - uses: ./.github/actions/ci
        with:
          project_file: pkgs/sdk/server/src/LaunchDarkly.ServerSdk.csproj
          test_project_file: pkgs/sdk/server/test/LaunchDarkly.ServerSdk.Tests.csproj

      - uses: ./.github/actions/contract-tests
        with:
          service_project_file: pkgs/sdk/server/contract-tests/TestService.csproj
          service_dll_file: pkgs/sdk/server/contract-tests/bin/debug/net6.0/ContractTestService.dll
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: ./.github/actions/build-docs
        with:
          workspace_path: pkgs/sdk/server
